- platform: mjpeg
  name: 'Bedroom camera'
  mjpeg_url: !secret motioneye_bedroom_ip
  still_image_url: !secret motioneye_bedroom_snapshot_ip
  authentication: 'basic'
  username: !secret motioneye_bedroom_user

- platform: mjpeg
  name: 'Garage camera'
  mjpeg_url: !secret motioneye_garage_ip
  still_image_url: !secret motioneye_garage_snapshot_ip
  authentication: 'basic'
  username: !secret motioneye_garage_user
