- platform: waze_travel_time
  name: 'Waze Home travel time'
  origin: !secret waze_work_coords
  destination: !secret waze_home_coords
  region: 'EU'

- platform: waze_travel_time
  name: 'Waze Work travel time'
  origin: !secret waze_home_coords
  destination: !secret waze_work_coords
  region: 'EU'
