- platform: yweather
  forecast: 1
  name: 'Today'
  monitored_conditions:
    - weather
    - temperature

- platform: yweather
  forecast: 2
  name: 'Tomorrow'
  monitored_conditions:
    - weather
    - temperature
